name: static_code_analysis_and_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Install library
        run: uv pip install -e ".[dev]"

      - name: Run tests
        run: uv run pytest tests

      - name: Run format check
        run: uvx pre-commit run --all-file
